-- MySQL Script generated by MySQL Workbench
-- mar 06 mar 2018 11:26:59 CST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mantenimiento
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mantenimiento` ;

-- -----------------------------------------------------
-- Schema mantenimiento
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mantenimiento` DEFAULT CHARACTER SET utf8 ;
USE `mantenimiento` ;

-- -----------------------------------------------------
-- Table `mantenimiento`.`modelo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`modelo` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`modelo` (
  `id_modelo` INT NOT NULL,
  `modelo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_modelo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`marca` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`marca` (
  `id_marca` INT NOT NULL,
  `marca` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_marca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`equipo` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`equipo` (
  `id_equipo` INT NOT NULL,
  `serie` VARCHAR(45) NOT NULL,
  `unidad` VARCHAR(45) NULL,
  PRIMARY KEY (`id_equipo`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`detalle_equipo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`detalle_equipo` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`detalle_equipo` (
  `id_detalle_equipo` INT NOT NULL,
  `dispositivo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `marca_id_marca` INT NOT NULL,
  `modelo_id_modelo` INT NOT NULL,
  `equipo_id_equipo` INT NOT NULL,
  PRIMARY KEY (`id_detalle_equipo`),
  INDEX `fk_detalle_equipo_marca_idx` (`marca_id_marca` ASC),
  INDEX `fk_detalle_equipo_modelo1_idx` (`modelo_id_modelo` ASC),
  INDEX `fk_detalle_equipo_equipo1_idx` (`equipo_id_equipo` ASC),
  CONSTRAINT `fk_detalle_equipo_marca`
    FOREIGN KEY (`marca_id_marca`)
    REFERENCES `mantenimiento`.`marca` (`id_marca`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_equipo_modelo1`
    FOREIGN KEY (`modelo_id_modelo`)
    REFERENCES `mantenimiento`.`modelo` (`id_modelo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_detalle_equipo_equipo1`
    FOREIGN KEY (`equipo_id_equipo`)
    REFERENCES `mantenimiento`.`equipo` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`tipo_mantenimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`tipo_mantenimiento` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`tipo_mantenimiento` (
  `id_tipo_mantenimiento` INT NOT NULL,
  `tipo_mantenimiento` VARCHAR(45) NOT NULL,
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`id_tipo_mantenimiento`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`solicitud`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`solicitud` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`solicitud` (
  `id_solicitud` INT NOT NULL,
  `fecha` VARCHAR(45) NOT NULL,
  `responsable` VARCHAR(45) NOT NULL,
  `email` VARCHAR(45) NULL,
  `telefono` VARCHAR(45) NULL,
  `descripcion` VARCHAR(45) NULL,
  `equipo_id_equipo` INT NOT NULL,
  `tipo_mantenimiento_id_tipo_mantenimiento` INT NOT NULL,
  PRIMARY KEY (`id_solicitud`),
  INDEX `fk_solicitud_equipo1_idx` (`equipo_id_equipo` ASC),
  INDEX `fk_solicitud_tipo_mantenimiento1_idx` (`tipo_mantenimiento_id_tipo_mantenimiento` ASC),
  CONSTRAINT `fk_solicitud_equipo1`
    FOREIGN KEY (`equipo_id_equipo`)
    REFERENCES `mantenimiento`.`equipo` (`id_equipo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_solicitud_tipo_mantenimiento1`
    FOREIGN KEY (`tipo_mantenimiento_id_tipo_mantenimiento`)
    REFERENCES `mantenimiento`.`tipo_mantenimiento` (`id_tipo_mantenimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`calendario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`calendario` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`calendario` (
  `id_calendario` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `descripcion` TEXT NULL,
  `responsable` VARCHAR(45) NOT NULL,
  `telefono` INT(8) NULL,
  `fecha_fin` DATE NULL,
  `cantidad` INT NOT NULL,
  PRIMARY KEY (`id_calendario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`orden_trabajo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`orden_trabajo` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`orden_trabajo` (
  `id_orden_trabajo` INT NOT NULL,
  `fecha_inicio` DATE NOT NULL,
  `prioridad` VARCHAR(45) NOT NULL,
  `solicitud_id_solicitud` INT NOT NULL,
  `calendario_id_calendario` INT NOT NULL,
  PRIMARY KEY (`id_orden_trabajo`),
  INDEX `fk_orden_trabajo_calendario1_idx` (`calendario_id_calendario` ASC),
  INDEX `fk_orden_trabajo_solicitud1_idx` (`solicitud_id_solicitud` ASC),
  CONSTRAINT `fk_orden_trabajo_solicitud1`
    FOREIGN KEY (`solicitud_id_solicitud`)
    REFERENCES `mantenimiento`.`solicitud` (`id_solicitud`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_trabajo_calendario1`
    FOREIGN KEY (`calendario_id_calendario`)
    REFERENCES `mantenimiento`.`calendario` (`id_calendario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`detalle_mantenimineto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`detalle_mantenimineto` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`detalle_mantenimineto` (
  `id_detalle_mantenimineto` INT NOT NULL,
  `hardware/sotfware` VARCHAR(45) NOT NULL,
  `detalle_sotfware` TEXT NULL,
  `detalle_hardware` TEXT NULL,
  `orden_trabajo_id_orden_trabajo` INT NOT NULL,
  PRIMARY KEY (`id_detalle_mantenimineto`),
  INDEX `fk_detalle_mantenimineto_orden_trabajo1_idx` (`orden_trabajo_id_orden_trabajo` ASC),
  CONSTRAINT `fk_detalle_mantenimineto_orden_trabajo1`
    FOREIGN KEY (`orden_trabajo_id_orden_trabajo`)
    REFERENCES `mantenimiento`.`orden_trabajo` (`id_orden_trabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`pasos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`pasos` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`pasos` (
  `id_paso` INT NOT NULL,
  `paso` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_paso`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`procedimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`procedimiento` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`procedimiento` (
  `id_procedimiento` INT NOT NULL,
  `tipo_procedimiento` VARCHAR(45) NULL,
  `pasos_id_paso` INT NOT NULL,
  PRIMARY KEY (`id_procedimiento`),
  INDEX `fk_procedimiento_pasos1_idx` (`pasos_id_paso` ASC),
  CONSTRAINT `fk_procedimiento_pasos1`
    FOREIGN KEY (`pasos_id_paso`)
    REFERENCES `mantenimiento`.`pasos` (`id_paso`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`estado_detalle_mantenimiento`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`estado_detalle_mantenimiento` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`estado_detalle_mantenimiento` (
  `id_estado_detalle_mantenimiento` INT NOT NULL,
  `estado` VARCHAR(45) NULL,
  `observaciones` VARCHAR(45) NULL,
  `detalle_mantenimineto_id_detalle_mantenimineto` INT NOT NULL,
  `procedimiento_id_procedimiento` INT NOT NULL,
  PRIMARY KEY (`id_estado_detalle_mantenimiento`),
  INDEX `fk_estado_detalle_mantenimiento_detalle_mantenimineto1_idx` (`detalle_mantenimineto_id_detalle_mantenimineto` ASC),
  INDEX `fk_estado_detalle_mantenimiento_procedimiento1_idx` (`procedimiento_id_procedimiento` ASC),
  CONSTRAINT `fk_estado_detalle_mantenimiento_detalle_mantenimineto1`
    FOREIGN KEY (`detalle_mantenimineto_id_detalle_mantenimineto`)
    REFERENCES `mantenimiento`.`detalle_mantenimineto` (`id_detalle_mantenimineto`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_estado_detalle_mantenimiento_procedimiento1`
    FOREIGN KEY (`procedimiento_id_procedimiento`)
    REFERENCES `mantenimiento`.`procedimiento` (`id_procedimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`diagnostico_parte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`diagnostico_parte` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`diagnostico_parte` (
  `id_diagnostico_parte` INT NOT NULL,
  `parte` VARCHAR(45) NOT NULL,
  `observaciones` VARCHAR(45) NULL,
  PRIMARY KEY (`id_diagnostico_parte`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`diagnostico`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`diagnostico` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`diagnostico` (
  `id_diagnostico` INT NOT NULL,
  `diagnostico` VARCHAR(45) NOT NULL,
  `procedimiento_id_procedimiento` INT NOT NULL,
  `diagnostico_parte_id_diagnostico_parte` INT NOT NULL,
  PRIMARY KEY (`id_diagnostico`),
  INDEX `fk_diagnostico_procedimiento1_idx` (`procedimiento_id_procedimiento` ASC),
  INDEX `fk_diagnostico_diagnostico_parte1_idx` (`diagnostico_parte_id_diagnostico_parte` ASC),
  CONSTRAINT `fk_diagnostico_procedimiento1`
    FOREIGN KEY (`procedimiento_id_procedimiento`)
    REFERENCES `mantenimiento`.`procedimiento` (`id_procedimiento`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_diagnostico_diagnostico_parte1`
    FOREIGN KEY (`diagnostico_parte_id_diagnostico_parte`)
    REFERENCES `mantenimiento`.`diagnostico_parte` (`id_diagnostico_parte`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`trabajadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`trabajadores` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`trabajadores` (
  `id_trabajador` INT NOT NULL,
  `nombres` VARCHAR(100) NOT NULL,
  `apellidos` VARCHAR(100) NOT NULL,
  `email` VARCHAR(45) NULL,
  PRIMARY KEY (`id_trabajador`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`cargo`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`cargo` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`cargo` (
  `id_cargo` INT NOT NULL,
  `cargo` VARCHAR(45) NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  `trabajadores_id_trabajador` INT NOT NULL,
  PRIMARY KEY (`id_cargo`),
  INDEX `fk_cargo_trabajadores1_idx` (`trabajadores_id_trabajador` ASC),
  CONSTRAINT `fk_cargo_trabajadores1`
    FOREIGN KEY (`trabajadores_id_trabajador`)
    REFERENCES `mantenimiento`.`trabajadores` (`id_trabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`orden_trabajo_por_trabajadores`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`orden_trabajo_por_trabajadores` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`orden_trabajo_por_trabajadores` (
  `orden_trabajo_id_orden_trabajo` INT NOT NULL,
  `trabajadores_id_trabajador` INT NOT NULL,
  `detalle_` TEXT NULL,
  PRIMARY KEY (`orden_trabajo_id_orden_trabajo`, `trabajadores_id_trabajador`),
  INDEX `fk_orden_trabajo_has_trabajadores_trabajadores1_idx` (`trabajadores_id_trabajador` ASC),
  INDEX `fk_orden_trabajo_has_trabajadores_orden_trabajo1_idx` (`orden_trabajo_id_orden_trabajo` ASC),
  CONSTRAINT `fk_orden_trabajo_has_trabajadores_orden_trabajo1`
    FOREIGN KEY (`orden_trabajo_id_orden_trabajo`)
    REFERENCES `mantenimiento`.`orden_trabajo` (`id_orden_trabajo`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_orden_trabajo_has_trabajadores_trabajadores1`
    FOREIGN KEY (`trabajadores_id_trabajador`)
    REFERENCES `mantenimiento`.`trabajadores` (`id_trabajador`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mantenimiento`.`asuetos`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mantenimiento`.`asuetos` ;

CREATE TABLE IF NOT EXISTS `mantenimiento`.`asuetos` (
  `id_asuetos` INT NOT NULL,
  `fecha` DATE NOT NULL,
  `descripcion` VARCHAR(45) NULL,
  PRIMARY KEY (`id_asuetos`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO marca(id_marca,marca,descripcion) VALUES(1,"DELL","PC");
INSERT INTO marca(id_marca,marca,descripcion) VALUES(2,"HP","PC");
INSERT INTO marca(id_marca,marca,descripcion) VALUES(3,"LENOVO","Laptop");


